name: Deploy to EC2

on:
  push:
    branches:
      - main   # תריץ deploy רק כשעושים push ל-main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.60.187.123 "
            cd ~/dev && \
            git pull origin main && \
            npm install && \
            npm run build && \
            pm2 restart myapp || pm2 start 'serve -s dist -l 80' --name myapp
          "
